name: Deploy Webapp
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting webapp deployment!"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up OCaml environment
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
      - run: opam install js_of_ocaml js_of_ocaml-ppx js_of_ocaml-lwt

      - name: Build project
        run: opam exec -- dune build webapp

      - name: Construct artifact
        run: |
          mkdir artifact
          cp webapp/artifact/ artifact/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: artifact

      - name: Cleanup
        run: rm -rf artifact